CREATE TABLE GENIE_PAGE (
	PAGE_ID	VARCHAR2(100),
	TITLE		VARCHAR2(100),
	PARAM1	VARCHAR2(100),
	PARAM2	VARCHAR2(100),
	PARAM3	VARCHAR2(100),
	PRIMARY KEY (PAGE_ID)
)
/

CREATE TABLE GENIE_PAGE_SQL (
	PAGE_ID	VARCHAR2(100),
	SEQ		NUMBER(3),
	TITLE		VARCHAR2(100),
	SQL_STMT	VARCHAR2(1000),
	INDENT	NUMBER(3)		DEFAULT 0,
	PRIMARY KEY (PAGE_ID, SEQ),
	FOREIGN KEY (PAGE_ID) REFERENCES GENIE_PAGE ON DELETE CASCADE
)
/

CREATE TABLE GENIE_WORK_SHEET (
	ID			VARCHAR2(100),
	SQL_STMTS	VARCHAR2(4000),
	COORDS		VARCHAR2(4000),
	UPDATED     DATE DEFAULT SYSDATE,
	PRIMARY KEY (ID)
)
/

CREATE TABLE GENIE_TABLE_COL (
	TNAME			VARCHAR2(30),
	CNAME			VARCHAR2(30),
	CAPT			VARCHAR2(30),
	LOOKUP_SQL		VARCHAR2(500),
	PRIMARY KEY (TNAME, CNAME)
)
/
