insert into GENIE_PAGE values ('member','CPAS Member Info', 'mkey', null, null);

insert into GENIE_PAGE_SQL values ('member',1,'MEMBER',
	'SELECT * FROM MEMBER WHERE MKEY=''[mkey]''', 0);

insert into GENIE_PAGE_SQL values ('member',2,'PERSON',
	'SELECT * FROM PERSON WHERE PERSONID IN (SELECT PERSONID FROM MEMBER WHERE MKEY=''[mkey]'')', 30);

insert into GENIE_PAGE_SQL values ('member',3,'CLIENT',
	'SELECT * FROM CLIENT WHERE CLIENT IN (SELECT CLNT FROM MEMBER WHERE MKEY=''[mkey]'')', 30);

insert into GENIE_PAGE_SQL values ('member',4,'PLAN',
	'SELECT * FROM PLAN WHERE PLAN IN (SELECT PLAN FROM MEMBER_PLAN WHERE MKEY=''[mkey]'')', 30);

insert into GENIE_PAGE_SQL values ('member',5,'ACCOUNT',
	'SELECT * FROM ACCOUNT WHERE ACCOUNTID IN (SELECT ACCOUNTID FROM MEMBER_PLAN_ACCOUNT WHERE MKEY=''[mkey]'')', 30);

insert into GENIE_PAGE_SQL values ('member',6,'ACCOUNT_FUND',
	'SELECT * FROM ACCOUNT_FUND WHERE ACCOUNTID IN (SELECT ACCOUNTID FROM MEMBER_PLAN_ACCOUNT WHERE MKEY=''[mkey]'')', 60);

insert into GENIE_PAGE_SQL values ('member',7,'ACCOUNT_FUND_TRANS',
	'SELECT * FROM ACCOUNT_FUND_TRANS WHERE ACCOUNTID IN (SELECT ACCOUNTID FROM MEMBER_PLAN_ACCOUNT WHERE MKEY=''[mkey]'')', 90);
